import type { Enquiry } from "../table-types/enquiry-types";
export const dummyEnquiries: Enquiry[] = [
  {
    id: "ENQ001",
    company_name: "Star Motors Pvt Ltd",
    primary_phone_number: "9876543210",
    whatsappPrimary: true,
    altNumber: "9123456780",
    whatsappAlt: false,
    email: "contact@starmotors.com",
    business_type: "Automobile",
    status: "Active",
    stage: "Negotiation",
    mainCategory: "Vehicles",
    subCategory: "Cars",
    location: "Mumbai, Maharashtra",
    source: "Website",
    budget: "₹10,00,000",
    remarks: "Interested in premium sedan models",
    pdf: null,
  },
  {
    id: "ENQ002",
    company_name: "Green Earth Supplies",
    primary_phone_number: "9988776655",
    whatsappPrimary: false,
    altNumber: "8899776655",
    whatsappAlt: true,
    email: "info@greenearth.com",
    business_type: "Manufacturing",
    status: "Pending",
    stage: "Initial Contact",
    mainCategory: "Industrial Supplies",
    subCategory: "Eco-friendly Packaging",
    location: "Delhi",
    source: "Trade Fair",
    budget: "₹3,00,000",
    remarks: "Looking for bulk eco-friendly packaging",
    pdf: null,
  },
  {
    id: "ENQ003",
    company_name: "TechNova Solutions",
    primary_phone_number: "9090909090",
    whatsappPrimary: true,
    altNumber: "8080808080",
    whatsappAlt: false,
    email: "sales@technova.com",
    business_type: "IT Services",
    status: "Closed Won",
    stage: "Finalized",
    mainCategory: "Software",
    subCategory: "CRM Systems",
    location: "Bangalore, Karnataka",
    source: "Referral",
    budget: "₹15,00,000",
    remarks: "Signed annual contract for CRM software",
    pdf: null,
  },
  {
    id: "ENQ004",
    company_name: "FreshMart Retailers",
    primary_phone_number: "9812345678",
    whatsappPrimary: false,
    altNumber: "9012345678",
    whatsappAlt: true,
    email: "hello@freshmart.com",
    business_type: "Retail",
    status: "Lost",
    stage: "Follow-up Missed",
    mainCategory: "FMCG",
    subCategory: "Grocery",
    location: "Chennai, Tamil Nadu",
    source: "Cold Call",
    budget: "₹5,00,000",
    remarks: "Moved to competitor due to pricing",
    pdf: null,
  },
];
