import type { pendingEnquiry } from "../table-types/pending-enquiry-types";

export const pendingEnquiryData: pendingEnquiry[] = [
  {
    sl: 1,
    Name: "ABC Traders",
    phone: "9876543210",
    user: "John Doe",
    status: "pending",
    budget: "5000",
    businessType: "Manufacturer",
    source: "Cold Calling",
  },
  {
    sl: 2,
    Name: "XYZ Services",
    phone: "9123456780",
    user: "Jane Smith",
    status: "pending",
    budget: "3000",
    businessType: "Service",
    source: "Social Media",
  },
  {
    sl: 3,
    Name: "PQR Solutions",
    phone: "9988776655",
    user: "Alice Johnson",
    status: "pending",
    budget: "8000",
    businessType: "Consulting",
    source: "Referral",
  },
  {
    sl: 4,
    Name: "LMN Industries",
    phone: "9871122334",
    user: "Bob Brown",
    status: "pending",
    budget: "4500",
    businessType: "Manufacturer",
    source: "Cold Calling",
  },
  {
    sl: 5,
    Name: "TechNova",
    phone: "9012345678",
    user: "Charlie White",
    status: "pending",
    budget: "6000",
    businessType: "Service",
    source: "Social Media",
  },
];
